spring.application.name=MinorProject-1JBDL93

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/jbdl93ELibrary?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oooooooo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

book.limit=15
finePerDay=100
issuePerStudentLimit=3