spring.application.name=b93Profiles

#system defined properties
server.port=8081

spring.datasource.url= "jdbc:mysql://localhost:3306/b93DB"
spring.datasource.username=root
spring.datasource.password=root


#user defined properties
paytm.users=
#integrate vault , it will automatically fill the = value in production

spring.profiles.active=beta,gamma,prod

logging.level.org.springframework.boot=error
logging.level.com.example.b93Profiles=info


#application-profile.properties


#try to print different logging level for different package or project ex (different for user defined and different for spring defined)
