server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/walletDB93?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oooooooo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

wallet.balance=10000