spring.application.name=jbdl93InDbSecurity


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/jbdl93InDbSecurity?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=oooooooo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=debug